import type { ExpandedAchievement } from './expandedAchievementService';

// CATEGORY-SPECIFIC ACHIEVEMENTS - Complete set for all 6 categories
export const CATEGORY_ACHIEVEMENTS: ExpandedAchievement[] = [
  // CARDIO CATEGORY (8 achievements)
  {
    id: 'cardio_starter',
    name: 'Cardio Starter',
    description: 'Complete your first cardio exercise',
    category: 'category_specific',
    icon: '❤️',
    badge_color: 'from-red-400 to-pink-500',
    rarity: 'common',
    points: 25,
    requirement: { type: 'category_specific', value: 1, conditions: { exercise_categories: ['cardio'] } },
    unlock_message: 'Your heart is pumping! First cardio exercise completed!',
    share_message: 'Started my cardio journey! ❤️ #InnerFire'
  },
  {
    id: 'cardio_streak_7',
    name: 'Cardio Week',
    description: '7-day cardio exercise streak',
    category: 'category_specific',
    icon: '💓',
    badge_color: 'from-red-500 to-rose-600',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'category_specific', value: 7, conditions: { exercise_categories: ['cardio'], consecutive: true } },
    unlock_message: 'One week of cardio dedication! Your heart loves you!',
    share_message: '7-day cardio streak completed! Heart strong! 💓 #InnerFire'
  },
  {
    id: 'cardio_25_sessions',
    name: 'Cardio Enthusiast',
    description: 'Complete 25 cardio sessions',
    category: 'category_specific',
    icon: '🏃‍♂️',
    badge_color: 'from-red-400 to-orange-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'category_specific', value: 25, conditions: { exercise_categories: ['cardio'] } },
    unlock_message: 'Twenty-five cardio sessions! You are a cardio enthusiast!',
    share_message: '25 cardio sessions completed! Enthusiast level! 🏃‍♂️ #InnerFire'
  },
  {
    id: 'cardio_lifetime_60min',
    name: 'Cardio Hour',
    description: 'Accumulate 60 minutes of cardio exercises',
    category: 'category_specific',
    icon: '⏰',
    badge_color: 'from-red-600 to-pink-700',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'category_specific', value: 3600, conditions: { exercise_categories: ['cardio'] } },
    unlock_message: 'One full hour of cardio! Your endurance is amazing!',
    share_message: '60 minutes of cardio completed! Endurance champion! ⏰ #InnerFire'
  },
  {
    id: 'cardio_consistency_21',
    name: 'Cardio Consistent',
    description: 'Do cardio exercises for 21 days within a month',
    category: 'category_specific',
    icon: '📅',
    badge_color: 'from-rose-500 to-red-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'category_specific', value: 21, conditions: { exercise_categories: ['cardio'], within_timeframe: 30 } },
    unlock_message: 'Incredible cardio consistency! 21 days in a month!',
    share_message: '21 cardio days this month! Consistency king! 📅 #InnerFire'
  },
  {
    id: 'cardio_streak_30',
    name: 'Cardio Month',
    description: '30-day cardio exercise streak',
    category: 'category_specific',
    icon: '🔥',
    badge_color: 'from-red-700 to-rose-800',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'category_specific', value: 30, conditions: { exercise_categories: ['cardio'], consecutive: true } },
    unlock_message: 'THIRTY DAYS of cardio! You are on fire!',
    share_message: '30-day cardio streak! I am on fire! 🔥 #InnerFire'
  },
  {
    id: 'cardio_mastery_100',
    name: 'Cardio Master',
    description: 'Complete 100 cardio sessions',
    category: 'category_specific',
    icon: '👑',
    badge_color: 'from-red-800 to-pink-900',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'category_specific', value: 100, conditions: { exercise_categories: ['cardio'] } },
    unlock_message: 'ONE HUNDRED cardio sessions! You are a cardio master!',
    share_message: '100 cardio sessions! Cardio master achieved! 👑 #InnerFire'
  },
  {
    id: 'cardio_lifetime_300min',
    name: 'Cardio Legend',
    description: 'Accumulate 5 hours (300 minutes) of cardio exercises',
    category: 'category_specific',
    icon: '🏆',
    badge_color: 'from-red-900 to-rose-900',
    rarity: 'legendary',
    points: 750,
    requirement: { type: 'category_specific', value: 18000, conditions: { exercise_categories: ['cardio'] } },
    unlock_message: 'FIVE HOURS of cardio! You are a cardio legend!',
    share_message: '5 hours of cardio completed! Cardio legend! 🏆 #InnerFire'
  },

  // LEG LIFT CATEGORY (8 achievements)
  {
    id: 'leg_lift_starter',
    name: 'Leg Lift Starter',
    description: 'Complete your first leg lift exercise',
    category: 'category_specific',
    icon: '🦵',
    badge_color: 'from-blue-400 to-cyan-500',
    rarity: 'common',
    points: 25,
    requirement: { type: 'category_specific', value: 1, conditions: { exercise_categories: ['leg_lift'] } },
    unlock_message: 'Legs up! First leg lift exercise completed!',
    share_message: 'Started my leg lift journey! 🦵 #InnerFire'
  },
  {
    id: 'leg_lift_streak_7',
    name: 'Leg Lift Week',
    description: '7-day leg lift exercise streak',
    category: 'category_specific',
    icon: '🦴',
    badge_color: 'from-blue-500 to-cyan-600',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'category_specific', value: 7, conditions: { exercise_categories: ['leg_lift'], consecutive: true } },
    unlock_message: 'One week of leg lifts! Your lower body is getting stronger!',
    share_message: '7-day leg lift streak! Lower body strong! 🦴 #InnerFire'
  },
  {
    id: 'leg_lift_25_sessions',
    name: 'Leg Lift Enthusiast',
    description: 'Complete 25 leg lift sessions',
    category: 'category_specific',
    icon: '💪',
    badge_color: 'from-blue-400 to-indigo-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'category_specific', value: 25, conditions: { exercise_categories: ['leg_lift'] } },
    unlock_message: 'Twenty-five leg lift sessions! You are a leg lift enthusiast!',
    share_message: '25 leg lift sessions completed! Enthusiast level! 💪 #InnerFire'
  },
  {
    id: 'leg_lift_lifetime_60min',
    name: 'Leg Lift Hour',
    description: 'Accumulate 60 minutes of leg lift exercises',
    category: 'category_specific',
    icon: '⏱️',
    badge_color: 'from-blue-600 to-cyan-700',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'category_specific', value: 3600, conditions: { exercise_categories: ['leg_lift'] } },
    unlock_message: 'One full hour of leg lifts! Your legs are incredibly strong!',
    share_message: '60 minutes of leg lifts! Leg strength champion! ⏱️ #InnerFire'
  },
  {
    id: 'leg_lift_consistency_21',
    name: 'Leg Lift Consistent',
    description: 'Do leg lift exercises for 21 days within a month',
    category: 'category_specific',
    icon: '🗓️',
    badge_color: 'from-cyan-500 to-blue-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'category_specific', value: 21, conditions: { exercise_categories: ['leg_lift'], within_timeframe: 30 } },
    unlock_message: 'Amazing leg lift consistency! 21 days in a month!',
    share_message: '21 leg lift days this month! Consistency champion! 🗓️ #InnerFire'
  },
  {
    id: 'leg_lift_streak_30',
    name: 'Leg Lift Month',
    description: '30-day leg lift exercise streak',
    category: 'category_specific',
    icon: '🔥',
    badge_color: 'from-blue-700 to-cyan-800',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'category_specific', value: 30, conditions: { exercise_categories: ['leg_lift'], consecutive: true } },
    unlock_message: 'THIRTY DAYS of leg lifts! Your dedication is incredible!',
    share_message: '30-day leg lift streak! Dedication level: epic! 🔥 #InnerFire'
  },
  {
    id: 'leg_lift_mastery_100',
    name: 'Leg Lift Master',
    description: 'Complete 100 leg lift sessions',
    category: 'category_specific',
    icon: '🏅',
    badge_color: 'from-blue-800 to-cyan-900',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'category_specific', value: 100, conditions: { exercise_categories: ['leg_lift'] } },
    unlock_message: 'ONE HUNDRED leg lift sessions! You are a leg lift master!',
    share_message: '100 leg lift sessions! Leg lift master achieved! 🏅 #InnerFire'
  },
  {
    id: 'leg_lift_lifetime_300min',
    name: 'Leg Lift Legend',
    description: 'Accumulate 5 hours (300 minutes) of leg lift exercises',
    category: 'category_specific',
    icon: '🏆',
    badge_color: 'from-blue-900 to-cyan-900',
    rarity: 'legendary',
    points: 750,
    requirement: { type: 'category_specific', value: 18000, conditions: { exercise_categories: ['leg_lift'] } },
    unlock_message: 'FIVE HOURS of leg lifts! You are a leg lift legend!',
    share_message: '5 hours of leg lifts! Leg lift legend! 🏆 #InnerFire'
  },

  // PLANKING CATEGORY (8 achievements)
  {
    id: 'planking_starter',
    name: 'Planking Starter', 
    description: 'Complete your first planking exercise',
    category: 'category_specific',
    icon: '🤲',
    badge_color: 'from-yellow-400 to-amber-500',
    rarity: 'common',
    points: 25,
    requirement: { type: 'category_specific', value: 1, conditions: { exercise_categories: ['planking'] } },
    unlock_message: 'Core engaged! First planking exercise completed!',
    share_message: 'Started my planking journey! 🤲 #InnerFire'
  },
  {
    id: 'planking_streak_7',
    name: 'Planking Week',
    description: '7-day planking exercise streak',
    category: 'category_specific',
    icon: '💛',
    badge_color: 'from-yellow-500 to-amber-600',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'category_specific', value: 7, conditions: { exercise_categories: ['planking'], consecutive: true } },
    unlock_message: 'One week of planking! Your core is getting solid!',
    share_message: '7-day planking streak! Core solid! 💛 #InnerFire'
  },
  {
    id: 'planking_25_sessions',
    name: 'Planking Enthusiast',
    description: 'Complete 25 planking sessions',
    category: 'category_specific',
    icon: '⭐',
    badge_color: 'from-yellow-400 to-orange-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'category_specific', value: 25, conditions: { exercise_categories: ['planking'] } },
    unlock_message: 'Twenty-five planking sessions! You are a planking enthusiast!',
    share_message: '25 planking sessions completed! Enthusiast level! ⭐ #InnerFire'
  },
  {
    id: 'planking_lifetime_60min',
    name: 'Planking Hour',
    description: 'Accumulate 60 minutes of planking exercises',
    category: 'category_specific',
    icon: '⏳',
    badge_color: 'from-yellow-600 to-amber-700',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'category_specific', value: 3600, conditions: { exercise_categories: ['planking'] } },
    unlock_message: 'One full hour of planking! Your core is rock solid!',
    share_message: '60 minutes of planking! Core rock solid! ⏳ #InnerFire'
  },
  {
    id: 'planking_consistency_21',
    name: 'Planking Consistent',
    description: 'Do planking exercises for 21 days within a month',
    category: 'category_specific',
    icon: '📊',
    badge_color: 'from-amber-500 to-yellow-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'category_specific', value: 21, conditions: { exercise_categories: ['planking'], within_timeframe: 30 } },
    unlock_message: 'Incredible planking consistency! 21 days in a month!',
    share_message: '21 planking days this month! Consistency master! 📊 #InnerFire'
  },
  {
    id: 'planking_streak_30',
    name: 'Planking Month',
    description: '30-day planking exercise streak',
    category: 'category_specific',
    icon: '🔥',
    badge_color: 'from-yellow-700 to-amber-800',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'category_specific', value: 30, conditions: { exercise_categories: ['planking'], consecutive: true } },
    unlock_message: 'THIRTY DAYS of planking! You are absolutely dedicated!',
    share_message: '30-day planking streak! Dedication level: epic! 🔥 #InnerFire'
  },
  {
    id: 'planking_mastery_100',
    name: 'Planking Master',
    description: 'Complete 100 planking sessions',
    category: 'category_specific',
    icon: '🏆',
    badge_color: 'from-yellow-800 to-amber-900',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'category_specific', value: 100, conditions: { exercise_categories: ['planking'] } },
    unlock_message: 'ONE HUNDRED planking sessions! You are a planking master!',
    share_message: '100 planking sessions! Planking master achieved! 🏆 #InnerFire'
  },
  {
    id: 'planking_lifetime_300min',
    name: 'Planking Legend',
    description: 'Accumulate 5 hours (300 minutes) of planking exercises',
    category: 'category_specific',
    icon: '👑',
    badge_color: 'from-yellow-900 to-amber-900',
    rarity: 'legendary',
    points: 750,
    requirement: { type: 'category_specific', value: 18000, conditions: { exercise_categories: ['planking'] } },
    unlock_message: 'FIVE HOURS of planking! You are a planking legend!',
    share_message: '5 hours of planking! Planking legend! 👑 #InnerFire'
  },

  // SEATED EXERCISE CATEGORY (8 achievements)
  {
    id: 'seated_starter',
    name: 'Seated Starter',
    description: 'Complete your first seated exercise',
    category: 'category_specific',
    icon: '🪑',
    badge_color: 'from-green-400 to-emerald-500',
    rarity: 'common',
    points: 25,
    requirement: { type: 'category_specific', value: 1, conditions: { exercise_categories: ['seated_exercise'] } },
    unlock_message: 'Seated and ready! First seated exercise completed!',
    share_message: 'Started my seated exercise journey! 🪑 #InnerFire'
  },
  {
    id: 'seated_streak_7',
    name: 'Seated Week',
    description: '7-day seated exercise streak',
    category: 'category_specific',
    icon: '💚',
    badge_color: 'from-green-500 to-emerald-600',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'category_specific', value: 7, conditions: { exercise_categories: ['seated_exercise'], consecutive: true } },
    unlock_message: 'One week of seated exercises! Consistency in comfort!',
    share_message: '7-day seated exercise streak! Comfortable consistency! 💚 #InnerFire'
  },
  {
    id: 'seated_25_sessions',
    name: 'Seated Enthusiast',
    description: 'Complete 25 seated exercise sessions',
    category: 'category_specific',
    icon: '🌱',
    badge_color: 'from-green-400 to-teal-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'category_specific', value: 25, conditions: { exercise_categories: ['seated_exercise'] } },
    unlock_message: 'Twenty-five seated sessions! You are a seated exercise enthusiast!',
    share_message: '25 seated exercise sessions! Enthusiast level! 🌱 #InnerFire'
  },
  {
    id: 'seated_lifetime_60min',
    name: 'Seated Hour',
    description: 'Accumulate 60 minutes of seated exercises',
    category: 'category_specific',
    icon: '⏲️',
    badge_color: 'from-green-600 to-emerald-700',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'category_specific', value: 3600, conditions: { exercise_categories: ['seated_exercise'] } },
    unlock_message: 'One full hour of seated exercises! Comfortable yet effective!',
    share_message: '60 minutes of seated exercises! Effective comfort! ⏲️ #InnerFire'
  },
  {
    id: 'seated_consistency_21',
    name: 'Seated Consistent',
    description: 'Do seated exercises for 21 days within a month',
    category: 'category_specific',
    icon: '📈',
    badge_color: 'from-emerald-500 to-green-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'category_specific', value: 21, conditions: { exercise_categories: ['seated_exercise'], within_timeframe: 30 } },
    unlock_message: 'Amazing seated exercise consistency! 21 days in a month!',
    share_message: '21 seated exercise days this month! Consistency expert! 📈 #InnerFire'
  },
  {
    id: 'seated_streak_30',
    name: 'Seated Month',
    description: '30-day seated exercise streak',
    category: 'category_specific',
    icon: '🔥',
    badge_color: 'from-green-700 to-emerald-800',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'category_specific', value: 30, conditions: { exercise_categories: ['seated_exercise'], consecutive: true } },
    unlock_message: 'THIRTY DAYS of seated exercises! Unstoppable dedication!',
    share_message: '30-day seated exercise streak! Unstoppable! 🔥 #InnerFire'
  },
  {
    id: 'seated_mastery_100',
    name: 'Seated Master',
    description: 'Complete 100 seated exercise sessions',
    category: 'category_specific',
    icon: '🎯',
    badge_color: 'from-green-800 to-emerald-900',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'category_specific', value: 100, conditions: { exercise_categories: ['seated_exercise'] } },
    unlock_message: 'ONE HUNDRED seated sessions! You are a seated exercise master!',
    share_message: '100 seated exercise sessions! Master achieved! 🎯 #InnerFire'
  },
  {
    id: 'seated_lifetime_300min',
    name: 'Seated Legend',
    description: 'Accumulate 5 hours (300 minutes) of seated exercises',
    category: 'category_specific',
    icon: '🏆',
    badge_color: 'from-green-900 to-emerald-900',
    rarity: 'legendary',
    points: 750,
    requirement: { type: 'category_specific', value: 18000, conditions: { exercise_categories: ['seated_exercise'] } },
    unlock_message: 'FIVE HOURS of seated exercises! You are a seated legend!',
    share_message: '5 hours of seated exercises! Seated legend! 🏆 #InnerFire'
  },

  // STANDING MOVEMENT CATEGORY (8 achievements)
  {
    id: 'standing_starter',
    name: 'Standing Starter',
    description: 'Complete your first standing movement exercise',
    category: 'category_specific',
    icon: '🧍',
    badge_color: 'from-purple-400 to-violet-500',
    rarity: 'common',
    points: 25,
    requirement: { type: 'category_specific', value: 1, conditions: { exercise_categories: ['standing_movement'] } },
    unlock_message: 'Standing tall! First standing movement completed!',
    share_message: 'Started my standing movement journey! 🧍 #InnerFire'
  },
  {
    id: 'standing_streak_7',
    name: 'Standing Week',
    description: '7-day standing movement streak',
    category: 'category_specific',
    icon: '💜',
    badge_color: 'from-purple-500 to-violet-600',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'category_specific', value: 7, conditions: { exercise_categories: ['standing_movement'], consecutive: true } },
    unlock_message: 'One week standing strong! Your posture is improving!',
    share_message: '7-day standing movement streak! Standing strong! 💜 #InnerFire'
  },
  {
    id: 'standing_25_sessions',
    name: 'Standing Enthusiast',
    description: 'Complete 25 standing movement sessions',
    category: 'category_specific',
    icon: '🚶‍♂️',
    badge_color: 'from-purple-400 to-indigo-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'category_specific', value: 25, conditions: { exercise_categories: ['standing_movement'] } },
    unlock_message: 'Twenty-five standing sessions! You are a standing movement enthusiast!',
    share_message: '25 standing movement sessions! Enthusiast level! 🚶‍♂️ #InnerFire'
  },
  {
    id: 'standing_lifetime_60min',
    name: 'Standing Hour',
    description: 'Accumulate 60 minutes of standing movements',
    category: 'category_specific',
    icon: '⌚',
    badge_color: 'from-purple-600 to-violet-700',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'category_specific', value: 3600, conditions: { exercise_categories: ['standing_movement'] } },
    unlock_message: 'One full hour of standing movements! Your balance is amazing!',
    share_message: '60 minutes of standing movements! Balance master! ⌚ #InnerFire'
  },
  {
    id: 'standing_consistency_21',
    name: 'Standing Consistent',
    description: 'Do standing movements for 21 days within a month',
    category: 'category_specific',
    icon: '📏',
    badge_color: 'from-violet-500 to-purple-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'category_specific', value: 21, conditions: { exercise_categories: ['standing_movement'], within_timeframe: 30 } },
    unlock_message: 'Outstanding standing consistency! 21 days in a month!',
    share_message: '21 standing movement days this month! Standing consistent! 📏 #InnerFire'
  },
  {
    id: 'standing_streak_30',
    name: 'Standing Month',
    description: '30-day standing movement streak',
    category: 'category_specific',
    icon: '🔥',
    badge_color: 'from-purple-700 to-violet-800',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'category_specific', value: 30, conditions: { exercise_categories: ['standing_movement'], consecutive: true } },
    unlock_message: 'THIRTY DAYS standing strong! You are remarkable!',
    share_message: '30-day standing movement streak! Remarkable! 🔥 #InnerFire'
  },
  {
    id: 'standing_mastery_100',
    name: 'Standing Master',
    description: 'Complete 100 standing movement sessions',
    category: 'category_specific',
    icon: '🎖️',
    badge_color: 'from-purple-800 to-violet-900',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'category_specific', value: 100, conditions: { exercise_categories: ['standing_movement'] } },
    unlock_message: 'ONE HUNDRED standing sessions! You are a standing movement master!',
    share_message: '100 standing movement sessions! Master achieved! 🎖️ #InnerFire'
  },
  {
    id: 'standing_lifetime_300min',
    name: 'Standing Legend',
    description: 'Accumulate 5 hours (300 minutes) of standing movements',
    category: 'category_specific',
    icon: '🏆',
    badge_color: 'from-purple-900 to-violet-900',
    rarity: 'legendary',
    points: 750,
    requirement: { type: 'category_specific', value: 18000, conditions: { exercise_categories: ['standing_movement'] } },
    unlock_message: 'FIVE HOURS of standing movements! You are a standing legend!',
    share_message: '5 hours of standing movements! Standing legend! 🏆 #InnerFire'
  },

  // STRENGTH CATEGORY (8 achievements)
  {
    id: 'strength_starter',
    name: 'Strength Starter',
    description: 'Complete your first strength exercise',
    category: 'category_specific',
    icon: '💪',
    badge_color: 'from-orange-400 to-red-500',
    rarity: 'common',
    points: 25,
    requirement: { type: 'category_specific', value: 1, conditions: { exercise_categories: ['strength'] } },
    unlock_message: 'Power unleashed! First strength exercise completed!',
    share_message: 'Started my strength journey! 💪 #InnerFire'
  },
  {
    id: 'strength_streak_7',
    name: 'Strength Week',
    description: '7-day strength exercise streak',
    category: 'category_specific',
    icon: '🧡',
    badge_color: 'from-orange-500 to-red-600',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'category_specific', value: 7, conditions: { exercise_categories: ['strength'], consecutive: true } },
    unlock_message: 'One week of strength! Your power is growing!',
    share_message: '7-day strength streak! Power growing! 🧡 #InnerFire'
  },
  {
    id: 'strength_25_sessions',
    name: 'Strength Enthusiast',
    description: 'Complete 25 strength exercise sessions',
    category: 'category_specific',
    icon: '🏋️‍♂️',
    badge_color: 'from-orange-400 to-amber-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'category_specific', value: 25, conditions: { exercise_categories: ['strength'] } },
    unlock_message: 'Twenty-five strength sessions! You are a strength enthusiast!',
    share_message: '25 strength sessions completed! Enthusiast level! 🏋️‍♂️ #InnerFire'
  },
  {
    id: 'strength_lifetime_60min',
    name: 'Strength Hour',
    description: 'Accumulate 60 minutes of strength exercises',
    category: 'category_specific',
    icon: '⏱️',
    badge_color: 'from-orange-600 to-red-700',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'category_specific', value: 3600, conditions: { exercise_categories: ['strength'] } },
    unlock_message: 'One full hour of strength! Your muscles are incredible!',
    share_message: '60 minutes of strength exercises! Muscle power! ⏱️ #InnerFire'
  },
  {
    id: 'strength_consistency_21',
    name: 'Strength Consistent',
    description: 'Do strength exercises for 21 days within a month',
    category: 'category_specific',
    icon: '💯',
    badge_color: 'from-red-500 to-orange-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'category_specific', value: 21, conditions: { exercise_categories: ['strength'], within_timeframe: 30 } },
    unlock_message: 'Incredible strength consistency! 21 days in a month!',
    share_message: '21 strength days this month! Strength consistent! 💯 #InnerFire'
  },
  {
    id: 'strength_streak_30',
    name: 'Strength Month',
    description: '30-day strength exercise streak',
    category: 'category_specific',
    icon: '🔥',
    badge_color: 'from-orange-700 to-red-800',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'category_specific', value: 30, conditions: { exercise_categories: ['strength'], consecutive: true } },
    unlock_message: 'THIRTY DAYS of strength! You are incredibly powerful!',
    share_message: '30-day strength streak! Incredibly powerful! 🔥 #InnerFire'
  },
  {
    id: 'strength_mastery_100',
    name: 'Strength Master',
    description: 'Complete 100 strength exercise sessions',
    category: 'category_specific',
    icon: '🏅',
    badge_color: 'from-orange-800 to-red-900',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'category_specific', value: 100, conditions: { exercise_categories: ['strength'] } },
    unlock_message: 'ONE HUNDRED strength sessions! You are a strength master!',
    share_message: '100 strength sessions! Strength master achieved! 🏅 #InnerFire'
  },
  {
    id: 'strength_lifetime_300min',
    name: 'Strength Legend',
    description: 'Accumulate 5 hours (300 minutes) of strength exercises',
    category: 'category_specific',
    icon: '🏆',
    badge_color: 'from-orange-900 to-red-900',
    rarity: 'legendary',
    points: 750,
    requirement: { type: 'category_specific', value: 18000, conditions: { exercise_categories: ['strength'] } },
    unlock_message: 'FIVE HOURS of strength! You are a strength legend!',
    share_message: '5 hours of strength exercises! Strength legend! 🏆 #InnerFire'
  }
];

// CROSS-CATEGORY ACHIEVEMENTS - Complete set
export const CROSS_CATEGORY_ACHIEVEMENTS: ExpandedAchievement[] = [
  // Multi-Category Explorer (5 achievements)
  {
    id: 'category_explorer_2',
    name: 'Category Explorer',
    description: 'Complete exercises in 2 different categories',
    category: 'cross_category',
    icon: '🗺️',
    badge_color: 'from-teal-400 to-cyan-500',
    rarity: 'common',
    points: 50,
    requirement: { type: 'cross_category', value: 2, conditions: { minimum_categories: 2 } },
    unlock_message: 'Exploring new territories! You\'ve tried 2 exercise categories!',
    share_message: 'Explored 2 exercise categories! Territory expanding! 🗺️ #InnerFire'
  },
  {
    id: 'category_explorer_3',
    name: 'Multi-Category Adventurer',
    description: 'Complete exercises in 3 different categories',
    category: 'cross_category', 
    icon: '🎒',
    badge_color: 'from-teal-500 to-blue-600',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'cross_category', value: 3, conditions: { minimum_categories: 3 } },
    unlock_message: 'Adventure calls! You\'ve conquered 3 exercise categories!',
    share_message: 'Adventured through 3 exercise categories! 🎒 #InnerFire'
  },
  {
    id: 'category_explorer_4',
    name: 'Fitness Wanderer',
    description: 'Complete exercises in 4 different categories',
    category: 'cross_category',
    icon: '🧭',
    badge_color: 'from-blue-500 to-indigo-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'cross_category', value: 4, conditions: { minimum_categories: 4 } },
    unlock_message: 'Wandering through fitness! You\'ve mastered 4 exercise categories!',
    share_message: 'Wandered through 4 exercise categories! 🧭 #InnerFire'
  },
  {
    id: 'category_explorer_5',
    name: 'Fitness Explorer',
    description: 'Complete exercises in 5 different categories',
    category: 'cross_category',
    icon: '🏔️',
    badge_color: 'from-indigo-500 to-purple-600',
    rarity: 'epic',
    points: 400,
    requirement: { type: 'cross_category', value: 5, conditions: { minimum_categories: 5 } },
    unlock_message: 'Exploring every peak! You\'ve conquered 5 exercise categories!',
    share_message: 'Explored 5 exercise categories! Peak conqueror! 🏔️ #InnerFire'
  },
  {
    id: 'category_explorer_all',
    name: 'Complete Fitness Explorer',  
    description: 'Complete exercises in all 6 categories',
    category: 'cross_category',
    icon: '🌍',
    badge_color: 'from-purple-600 to-pink-700',
    rarity: 'legendary',
    points: 800,
    requirement: { type: 'cross_category', value: 6, conditions: { minimum_categories: 6 } },
    unlock_message: 'WORLD EXPLORER! You\'ve mastered ALL 6 exercise categories!',
    share_message: 'Explored ALL 6 exercise categories! World explorer! 🌍 #InnerFire'
  },

  // Same-Day Multi-Category (5 achievements)
  {
    id: 'same_day_2_categories',
    name: 'Daily Variety',
    description: 'Complete exercises from 2 categories in one day',
    category: 'cross_category',
    icon: '🌅',
    badge_color: 'from-pink-400 to-rose-500',
    rarity: 'uncommon',
    points: 75,
    requirement: { type: 'cross_category', value: 2, conditions: { same_day: true, minimum_categories: 2 } },
    unlock_message: 'Variety is the spice of life! 2 categories in one day!',
    share_message: '2 exercise categories in one day! Daily variety! 🌅 #InnerFire'
  },
  {
    id: 'same_day_3_categories',
    name: 'Triple Threat',
    description: 'Complete exercises from 3 categories in one day',
    category: 'cross_category',
    icon: '🎯',
    badge_color: 'from-rose-400 to-pink-600',
    rarity: 'rare',
    points: 150,
    requirement: { type: 'cross_category', value: 3, conditions: { same_day: true, minimum_categories: 3 } },
    unlock_message: 'Triple threat activated! 3 categories conquered in one day!',
    share_message: '3 exercise categories in one day! Triple threat! 🎯 #InnerFire'
  },
  {
    id: 'same_day_4_categories',
    name: 'Quadruple Power',
    description: 'Complete exercises from 4 categories in one day',
    category: 'cross_category',
    icon: '💥',
    badge_color: 'from-pink-500 to-purple-700',
    rarity: 'epic',
    points: 300,
    requirement: { type: 'cross_category', value: 4, conditions: { same_day: true, minimum_categories: 4 } },
    unlock_message: 'QUADRUPLE POWER! 4 categories mastered in one incredible day!',
    share_message: '4 exercise categories in one day! Quadruple power! 💥 #InnerFire'
  },
  {
    id: 'same_day_5_categories',
    name: 'Fitness Tornado',
    description: 'Complete exercises from 5 categories in one day',
    category: 'cross_category',
    icon: '🌪️',
    badge_color: 'from-purple-600 to-indigo-800',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'cross_category', value: 5, conditions: { same_day: true, minimum_categories: 5 } },
    unlock_message: 'FITNESS TORNADO! 5 categories destroyed in one day!',
    share_message: '5 exercise categories in one day! Fitness tornado! 🌪️ #InnerFire'
  },
  {
    id: 'same_day_all_categories',
    name: 'Fitness Hurricane',
    description: 'Complete exercises from all 6 categories in one day',
    category: 'cross_category',
    icon: '🌀',
    badge_color: 'from-indigo-700 to-purple-900',
    rarity: 'legendary',
    points: 1000,
    requirement: { type: 'cross_category', value: 6, conditions: { same_day: true, minimum_categories: 6 } },
    unlock_message: 'FITNESS HURRICANE! ALL 6 categories conquered in ONE DAY!',
    share_message: 'ALL 6 exercise categories in ONE DAY! Fitness hurricane! 🌀 #InnerFire'
  },

  // Weekly Multi-Category Variety (5 achievements)
  {
    id: 'weekly_variety_3',
    name: 'Weekly Variety Seeker',
    description: 'Complete exercises from 3 categories in one week',
    category: 'cross_category',
    icon: '🗓️',
    badge_color: 'from-cyan-400 to-blue-500',
    rarity: 'uncommon',
    points: 100,
    requirement: { type: 'cross_category', value: 3, conditions: { minimum_categories: 3, within_timeframe: 7 } },
    unlock_message: 'Weekly variety master! 3 categories in one week!',
    share_message: '3 exercise categories this week! Variety seeker! 🗓️ #InnerFire'
  },
  {
    id: 'weekly_variety_4',
    name: 'Weekly Variety Expert',
    description: 'Complete exercises from 4 categories in one week',
    category: 'cross_category',
    icon: '📅',
    badge_color: 'from-blue-500 to-indigo-600',
    rarity: 'rare',
    points: 200,
    requirement: { type: 'cross_category', value: 4, conditions: { minimum_categories: 4, within_timeframe: 7 } },
    unlock_message: 'Weekly variety expert! 4 categories conquered in one week!',
    share_message: '4 exercise categories this week! Variety expert! 📅 #InnerFire'
  },
  {
    id: 'weekly_variety_5',
    name: 'Weekly Variety Master',
    description: 'Complete exercises from 5 categories in one week',
    category: 'cross_category',
    icon: '🎯',
    badge_color: 'from-indigo-500 to-purple-600',
    rarity: 'epic',
    points: 350,
    requirement: { type: 'cross_category', value: 5, conditions: { minimum_categories: 5, within_timeframe: 7 } },
    unlock_message: 'Weekly variety master! 5 categories mastered in one week!',
    share_message: '5 exercise categories this week! Variety master! 🎯 #InnerFire'
  },
  {
    id: 'weekly_variety_all',
    name: 'Weekly Complete Explorer',
    description: 'Complete exercises from all 6 categories in one week',
    category: 'cross_category',
    icon: '🌟',
    badge_color: 'from-purple-600 to-pink-700',
    rarity: 'epic',
    points: 500,
    requirement: { type: 'cross_category', value: 6, conditions: { minimum_categories: 6, within_timeframe: 7 } },
    unlock_message: 'WEEKLY COMPLETE EXPLORER! All 6 categories in one week!',
    share_message: 'ALL 6 categories in one week! Complete explorer! 🌟 #InnerFire'
  },
  {
    id: 'consistency_across_categories',
    name: 'Cross-Category Consistency',
    description: 'Complete exercises from 4+ categories for 4 consecutive weeks',
    category: 'cross_category',
    icon: '🎪',
    badge_color: 'from-pink-600 to-rose-700',
    rarity: 'legendary',
    points: 1000,
    requirement: { type: 'cross_category', value: 28, conditions: { minimum_categories: 4, consecutive: true } },
    unlock_message: 'CROSS-CATEGORY CONSISTENCY MASTER! 4 weeks of 4+ categories!',
    share_message: '4+ categories for 4 consecutive weeks! Consistency master! 🎪 #InnerFire'
  },

  // Advanced Multi-Category Mastery (7 achievements)
  {
    id: 'balanced_trainer_50',
    name: 'Balanced Trainer',
    description: 'Complete 50+ sessions with at least 8 sessions in each category',
    category: 'cross_category',
    icon: '⚖️',
    badge_color: 'from-emerald-500 to-teal-600',
    rarity: 'rare',
    points: 300,
    requirement: { type: 'cross_category', value: 50, conditions: { minimum_categories: 6, balanced_requirement: 8 } },
    unlock_message: 'Perfectly balanced trainer! 8+ sessions in each category!',
    share_message: 'Balanced across all categories! Balanced trainer! ⚖️ #InnerFire'
  },
  {
    id: 'category_mastery_streak_14',
    name: 'Multi-Category Streak Master',
    description: 'Complete exercises from 3+ categories for 14 consecutive days',
    category: 'cross_category',
    icon: '🔗',
    badge_color: 'from-teal-500 to-cyan-600',
    rarity: 'epic',
    points: 400,
    requirement: { type: 'cross_category', value: 14, conditions: { minimum_categories: 3, consecutive: true } },
    unlock_message: 'Multi-category streak master! 14 days of variety!',
    share_message: '14-day multi-category streak! Streak master! 🔗 #InnerFire'
  },
  {
    id: 'fitness_philosopher_10h',
    name: 'Fitness Philosopher',
    description: 'Accumulate 10+ hours across all 6 exercise categories',
    category: 'cross_category',
    icon: '🧠',
    badge_color: 'from-cyan-600 to-blue-700',
    rarity: 'legendary',
    points: 1500,
    requirement: { type: 'cross_category', value: 36000, conditions: { minimum_categories: 6, duration_based: true } },
    unlock_message: 'FITNESS PHILOSOPHER! 10+ hours mastered across all categories!',
    share_message: '10+ hours across all categories! Fitness philosopher! 🧠 #InnerFire'
  },
  {
    id: 'category_perfectionist',
    name: 'Category Perfectionist',
    description: 'Complete 25+ sessions in each of the 6 categories',
    category: 'cross_category',
    icon: '💎',
    badge_color: 'from-blue-700 to-indigo-800',
    rarity: 'legendary',
    points: 2000,
    requirement: { type: 'cross_category', value: 150, conditions: { minimum_categories: 6, perfectionist_requirement: 25 } },
    unlock_message: 'CATEGORY PERFECTIONIST! 25+ sessions in every single category!',
    share_message: '25+ sessions in EVERY category! Perfectionist! 💎 #InnerFire'
  },
  {
    id: 'ultimate_fitness_explorer',
    name: 'Ultimate Fitness Explorer',
    description: 'Complete 500+ total sessions with representation in all categories',
    category: 'cross_category',
    icon: '🚀',
    badge_color: 'from-indigo-800 to-purple-900',
    rarity: 'legendary',
    points: 3000,
    requirement: { type: 'cross_category', value: 500, conditions: { minimum_categories: 6, ultimate_explorer: true } },
    unlock_message: 'ULTIMATE FITNESS EXPLORER! 500+ sessions across all categories!',
    share_message: '500+ sessions across ALL categories! Ultimate explorer! 🚀 #InnerFire'
  },
  {
    id: 'category_champion_100',
    name: 'Multi-Category Champion',
    description: 'Reach 100+ sessions in at least 3 different categories',
    category: 'cross_category',
    icon: '🏆',
    badge_color: 'from-purple-800 to-pink-900',
    rarity: 'legendary',
    points: 2500,
    requirement: { type: 'cross_category', value: 300, conditions: { minimum_categories: 3, champion_requirement: 100 } },
    unlock_message: 'MULTI-CATEGORY CHAMPION! 100+ sessions in 3+ categories!',
    share_message: '100+ sessions in 3+ categories! Multi-category champion! 🏆 #InnerFire'
  },
  {
    id: 'fitness_renaissance',
    name: 'Fitness Renaissance Master',
    description: 'Achieve mastery (50+ sessions) in all 6 exercise categories',
    category: 'cross_category',
    icon: '👑',
    badge_color: 'from-pink-900 to-rose-900',
    rarity: 'legendary',
    points: 5000,
    requirement: { type: 'cross_category', value: 300, conditions: { minimum_categories: 6, renaissance_requirement: 50 } },
    unlock_message: 'FITNESS RENAISSANCE MASTER! 50+ sessions in ALL 6 categories!',
    share_message: 'Mastered ALL 6 categories! Fitness Renaissance! 👑 #InnerFire'
  }
];
