-- Seed Exercise Data: ~62 exercises across 6 categories
-- This populates the exercises table created in Phase 1

-- Get category IDs for reference
DO $$
DECLARE
  cardio_id UUID;
  strength_id UUID;
  flexibility_id UUID;
  core_id UUID;
  balance_id UUID;
  endurance_id UUID;
BEGIN
  SELECT id INTO cardio_id FROM exercise_categories WHERE name = 'Cardio';
  SELECT id INTO strength_id FROM exercise_categories WHERE name = 'Strength';
  SELECT id INTO flexibility_id FROM exercise_categories WHERE name = 'Flexibility';
  SELECT id INTO core_id FROM exercise_categories WHERE name = 'Core';
  SELECT id INTO balance_id FROM exercise_categories WHERE name = 'Balance';
  SELECT id INTO endurance_id FROM exercise_categories WHERE name = 'Endurance';

  -- CARDIO EXERCISES (10 exercises)
  INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, description, instructions, benefits, modifications, cautions, tier_required, display_order) VALUES
  ('Jumping Jacks', cardio_id, 1, 30, 'Classic full-body cardio exercise', 'Stand with feet together. Jump while spreading legs and raising arms overhead. Return to start.', ARRAY['Increases heart rate', 'Burns calories', 'Improves coordination'], ARRAY['Step side to side instead of jumping', 'Remove arm movement'], ARRAY['Avoid if you have knee or ankle issues'], 'free', 1),
  ('High Knees', cardio_id, 2, 45, 'Running in place with high knee lifts', 'Run in place, lifting knees to hip height with each step. Pump arms naturally.', ARRAY['Strengthens hip flexors', 'Boosts cardiovascular fitness', 'Improves running form'], ARRAY['March in place with lower knee lifts', 'Hold onto a chair for balance'], ARRAY['Use caution with knee problems'], 'free', 2),
  ('Butt Kicks', cardio_id, 2, 45, 'Running in place kicking heels to glutes', 'Jog in place, kicking heels up toward your glutes with each step.', ARRAY['Activates hamstrings', 'Warms up leg muscles', 'Improves agility'], ARRAY['Slow down the pace', 'Reduce range of motion'], ARRAY['Avoid if you have hamstring strains'], 'free', 3),
  ('Mountain Climbers', cardio_id, 3, 60, 'Dynamic plank variation with alternating knee drives', 'Start in plank position. Quickly alternate bringing knees toward chest.', ARRAY['Full-body workout', 'Core activation', 'Cardiovascular conditioning'], ARRAY['Slow down the pace', 'Place hands on elevated surface'], ARRAY['Not recommended for wrist pain'], 'free', 4),
  ('Burpees', cardio_id, 4, 60, 'Full-body explosive movement combining squat, plank, and jump', 'Squat down, place hands on floor, jump feet back to plank, return feet, jump up.', ARRAY['Burns maximum calories', 'Builds explosive power', 'Full-body conditioning'], ARRAY['Remove the jump', 'Step back instead of jumping', 'Skip the push-up'], ARRAY['High impact - use caution with joint issues'], 'free', 5),
  ('Jump Rope (No Rope)', cardio_id, 2, 60, 'Simulated jump rope movements', 'Jump continuously while rotating wrists as if holding a rope.', ARRAY['Improves coordination', 'Builds calf strength', 'Excellent cardio'], ARRAY['Do single bounces instead of double-unders', 'March with arm rotations'], ARRAY['Avoid with ankle or knee pain'], 'premium', 6),
  ('Speed Skaters', cardio_id, 3, 60, 'Side-to-side jumping movements', 'Leap side to side, landing on one foot while sweeping the other behind.', ARRAY['Lateral movement training', 'Balance improvement', 'Leg strength'], ARRAY['Step side to side instead of jumping', 'Reduce range of motion'], ARRAY['Use caution on slippery surfaces'], 'premium', 7),
  ('Sprint in Place', cardio_id, 4, 30, 'Maximum effort running in place', 'Run in place as fast as possible with high knees and pumping arms.', ARRAY['Builds explosive power', 'Maximum calorie burn', 'Improves speed'], ARRAY['Reduce intensity', 'Focus on form over speed'], ARRAY['High intensity - warm up first'], 'premium', 8),
  ('Lateral Shuffles', cardio_id, 2, 60, 'Side-to-side shuffling movements', 'Shuffle laterally, keeping knees bent and chest up. Touch the floor at each end.', ARRAY['Agility training', 'Lateral strength', 'Hip mobility'], ARRAY['Reduce range of motion', 'Remove floor touches'], ARRAY['Watch for knee alignment'], 'free', 9),
  ('Box Steps', cardio_id, 1, 60, 'Stepping up and down pattern', 'Step up and down in a rhythmic pattern: up-up-down-down.', ARRAY['Low-impact cardio', 'Coordination training', 'Leg endurance'], ARRAY['Use a lower step height', 'Slow down the pace'], ARRAY['Use stable surface only'], 'free', 10);

  -- STRENGTH EXERCISES (11 exercises)
  INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, description, instructions, benefits, modifications, cautions, tier_required, display_order) VALUES
  ('Push-Ups', strength_id, 2, 30, 'Classic upper body strength exercise', 'Start in plank. Lower body until chest nearly touches floor. Push back up.', ARRAY['Builds chest strength', 'Strengthens triceps', 'Core activation'], ARRAY['Knee push-ups', 'Wall push-ups', 'Incline push-ups'], ARRAY['Maintain neutral spine throughout'], 'free', 1),
  ('Bodyweight Squats', strength_id, 1, 45, 'Fundamental lower body exercise', 'Stand with feet shoulder-width apart. Lower hips back and down. Return to standing.', ARRAY['Strengthens legs', 'Improves mobility', 'Functional movement'], ARRAY['Hold onto support', 'Reduce depth'], ARRAY['Keep knees tracking over toes'], 'free', 2),
  ('Lunges', strength_id, 2, 60, 'Single-leg strength and balance exercise', 'Step forward with one leg, lowering hips until both knees are at 90 degrees. Push back.', ARRAY['Leg strength', 'Balance training', 'Hip flexibility'], ARRAY['Static lunges', 'Shorter range'], ARRAY['Keep front knee over ankle'], 'free', 3),
  ('Tricep Dips', strength_id, 3, 30, 'Bodyweight tricep exercise using chair or bench', 'Sit on edge of chair, hands beside hips. Slide forward, lower body, push back up.', ARRAY['Tricep strength', 'Shoulder stability', 'Upper body endurance'], ARRAY['Keep feet closer', 'Reduce range of motion'], ARRAY['Avoid if you have shoulder pain'], 'free', 4),
  ('Wall Sit', strength_id, 2, 45, 'Isometric quad strengthening exercise', 'Lean back against wall with knees at 90 degrees. Hold position.', ARRAY['Quadriceps endurance', 'Isometric strength', 'Mental toughness'], ARRAY['Higher angle (less deep)', 'Hold for less time'], ARRAY['Keep knees aligned with toes'], 'free', 5),
  ('Diamond Push-Ups', strength_id, 4, 30, 'Advanced push-up variation targeting triceps', 'Push-up position with hands forming diamond shape. Lower and push up.', ARRAY['Maximum tricep activation', 'Chest definition', 'Core strength'], ARRAY['Perform on knees', 'Wider hand position'], ARRAY['Advanced exercise - master regular push-ups first'], 'premium', 6),
  ('Single-Leg Deadlifts', strength_id, 3, 60, 'Balance and hamstring strengthening', 'Stand on one leg, hinge at hip, reach toward floor. Return to standing.', ARRAY['Hamstring strength', 'Balance improvement', 'Hip stability'], ARRAY['Hold wall for support', 'Reduce range'], ARRAY['Keep back straight throughout'], 'premium', 7),
  ('Bulgarian Split Squats', strength_id, 4, 60, 'Advanced single-leg strength exercise', 'Rear foot elevated on chair. Lower front leg into lunge. Push back up.', ARRAY['Quad and glute strength', 'Balance training', 'Unilateral development'], ARRAY['Lower elevation', 'Hold support'], ARRAY['Master regular lunges first'], 'premium', 8),
  ('Pike Push-Ups', strength_id, 3, 30, 'Shoulder-focused push-up variation', 'Start in downward dog position. Bend elbows to lower head toward floor. Push up.', ARRAY['Shoulder strength', 'Prepares for handstands', 'Upper body power'], ARRAY['Elevate hands', 'Reduce depth'], ARRAY['Requires shoulder mobility'], 'premium', 9),
  ('Glute Bridges', strength_id, 1, 45, 'Hip and glute activation exercise', 'Lie on back, knees bent, feet flat. Lift hips to create straight line. Lower down.', ARRAY['Glute activation', 'Lower back health', 'Hip mobility'], ARRAY['Reduce range', 'Pause at top'], ARRAY['Keep core engaged'], 'free', 10),
  ('Calf Raises', strength_id, 1, 60, 'Lower leg strengthening', 'Stand on toes, raising heels as high as possible. Lower with control.', ARRAY['Calf strength', 'Ankle stability', 'Balance improvement'], ARRAY['Hold wall for support', 'Single leg variation'], ARRAY['Full range of motion for best results'], 'free', 11);

  -- FLEXIBILITY EXERCISES (10 exercises)
  INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, description, instructions, benefits, modifications, cautions, tier_required, display_order) VALUES
  ('Standing Forward Fold', flexibility_id, 1, 45, 'Hamstring and back stretch', 'Stand tall, hinge at hips, reach toward toes. Let upper body hang.', ARRAY['Hamstring flexibility', 'Spinal decompression', 'Calming effect'], ARRAY['Bend knees slightly', 'Hold onto shins'], ARRAY['Avoid bouncing movements'], 'free', 1),
  ('Cat-Cow Stretch', flexibility_id, 1, 60, 'Spinal mobility exercise', 'On hands and knees, alternate arching and rounding your spine.', ARRAY['Spinal flexibility', 'Core warming', 'Back pain relief'], ARRAY['Reduce range of motion', 'Slower pace'], ARRAY['Move gently if you have back issues'], 'free', 2),
  ('Child''s Pose', flexibility_id, 1, 60, 'Resting yoga pose and back stretch', 'Kneel, sit back on heels, reach arms forward on floor. Relax.', ARRAY['Back relaxation', 'Hip flexibility', 'Stress reduction'], ARRAY['Place pillow under knees', 'Arms at sides instead'], ARRAY['Avoid if pregnant'], 'free', 3),
  ('Hip Flexor Stretch', flexibility_id, 2, 45, 'Stretch for front of hip', 'Kneeling lunge position. Push hips forward gently until stretch is felt.', ARRAY['Hip flexibility', 'Posture improvement', 'Lower back relief'], ARRAY['Use pad under knee', 'Reduce depth'], ARRAY['Keep back straight'], 'free', 4),
  ('Seated Butterfly', flexibility_id, 2, 60, 'Inner thigh and hip stretch', 'Sit with soles of feet together. Gently press knees toward floor.', ARRAY['Hip opening', 'Inner thigh flexibility', 'Groin stretch'], ARRAY['Sit on cushion', 'Move feet further from body'], ARRAY['Never force the stretch'], 'free', 5),
  ('Quad Stretch', flexibility_id, 1, 30, 'Standing quadriceps stretch', 'Stand on one leg, pull other foot toward glutes. Hold.', ARRAY['Quadriceps flexibility', 'Balance practice', 'Improves knee health'], ARRAY['Hold wall for support', 'Reduce intensity'], ARRAY['Keep knees together'], 'free', 6),
  ('Thread the Needle', flexibility_id, 2, 45, 'Shoulder and upper back stretch', 'On hands and knees, thread one arm under body. Hold stretch.', ARRAY['Shoulder mobility', 'Upper back release', 'Thoracic spine flexibility'], ARRAY['Use pillow under shoulder', 'Less rotation'], ARRAY['Move slowly into position'], 'premium', 7),
  ('Pigeon Pose', flexibility_id, 3, 60, 'Deep hip opener from yoga', 'Front leg bent at 90 degrees, back leg extended. Fold forward.', ARRAY['Deep hip flexibility', 'Glute stretch', 'Hip pain relief'], ARRAY['Use props under hip', 'Reclined version'], ARRAY['Advanced stretch - ease into it'], 'premium', 8),
  ('Scorpion Stretch', flexibility_id, 4, 60, 'Advanced spinal rotation stretch', 'Lie face down, rotate one leg across body, keeping shoulders down.', ARRAY['Spinal rotation', 'Hip flexibility', 'Core stretch'], ARRAY['Reduce rotation', 'Use support'], ARRAY['Advanced stretch - progress slowly'], 'premium', 9),
  ('Standing Side Bend', flexibility_id, 1, 45, 'Lateral torso stretch', 'Stand tall, reach one arm overhead and bend to the side. Hold.', ARRAY['Lateral flexibility', 'Oblique stretch', 'Posture improvement'], ARRAY['Hold onto something', 'Reduce range'], ARRAY['Keep hips stable'], 'free', 10);

  -- CORE EXERCISES (11 exercises)
  INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, description, instructions, benefits, modifications, cautions, tier_required, display_order) VALUES
  ('Plank Hold', core_id, 2, 30, 'Isometric core strengthening exercise', 'Hold push-up position with forearms on ground. Keep body straight.', ARRAY['Core stability', 'Full-body tension', 'Posture improvement'], ARRAY['Plank from knees', 'Hands instead of forearms'], ARRAY['Keep neutral spine - no sagging'], 'free', 1),
  ('Dead Bug', core_id, 2, 60, 'Core control exercise on back', 'Lie on back, alternate extending opposite arm and leg while keeping back flat.', ARRAY['Core control', 'Coordination', 'Lower back protection'], ARRAY['Keep knees bent throughout', 'Slower pace'], ARRAY['Press lower back into floor'], 'free', 2),
  ('Bird Dog', core_id, 2, 60, 'Balance and core stability exercise', 'On hands and knees, extend opposite arm and leg. Hold, then switch.', ARRAY['Core stability', 'Balance', 'Back strength'], ARRAY['Just lift arm or leg, not both', 'Reduce hold time'], ARRAY['Keep hips level'], 'free', 3),
  ('Bicycle Crunches', core_id, 3, 45, 'Dynamic ab exercise with rotation', 'Lie on back, alternate bringing elbow to opposite knee in cycling motion.', ARRAY['Oblique strength', 'Ab definition', 'Core rotation'], ARRAY['Slower pace', 'Hands behind ears not head'], ARRAY['Don''t pull on neck'], 'free', 4),
  ('Russian Twists', core_id, 3, 45, 'Seated rotational core exercise', 'Sit with feet elevated, twist torso side to side touching floor beside hips.', ARRAY['Oblique strength', 'Rotational power', 'Core endurance'], ARRAY['Keep feet on ground', 'Reduce rotation'], ARRAY['Maintain upright posture'], 'free', 5),
  ('Side Plank', core_id, 3, 30, 'Lateral core strengthening', 'Balance on one forearm and side of foot. Hold body in straight line.', ARRAY['Oblique strength', 'Lateral stability', 'Shoulder strength'], ARRAY['Bottom knee on ground', 'Reduce hold time'], ARRAY['Keep body aligned'], 'free', 6),
  ('Hollow Hold', core_id, 4, 30, 'Advanced core tension exercise', 'Lie on back, lift shoulders and legs, creating hollow body shape. Hold.', ARRAY['Deep core strength', 'Body tension', 'Gymnastics foundation'], ARRAY['Keep knees bent', 'Higher leg position'], ARRAY['Press lower back down'], 'premium', 7),
  ('Dragon Flag', core_id, 5, 30, 'Extremely advanced core exercise', 'Lying down, lift entire body keeping it straight, supported only by shoulders.', ARRAY['Maximum core strength', 'Full-body control', 'Advanced training'], ARRAY['Single leg dragon flag', 'Negative repetitions'], ARRAY['Very advanced - master prerequisites first'], 'premium', 8),
  ('L-Sit Hold', core_id, 4, 30, 'Seated isometric core exercise', 'Sit with hands beside hips, lift body and legs off ground into L-shape.', ARRAY['Hip flexor strength', 'Core power', 'Compression strength'], ARRAY['One leg at a time', 'Bent knees'], ARRAY['Requires significant strength'], 'premium', 9),
  ('Windshield Wipers', core_id, 4, 45, 'Advanced rotational core exercise', 'Hang from bar or lie down, rotate legs side to side with control.', ARRAY['Oblique strength', 'Hip mobility', 'Advanced core control'], ARRAY['Knees bent throughout', 'Smaller range'], ARRAY['Very challenging - progress slowly'], 'premium', 10),
  ('Flutter Kicks', core_id, 2, 45, 'Lower ab targeting exercise', 'Lie on back, lift legs slightly, alternate small up and down kicks.', ARRAY['Lower ab strength', 'Hip flexor endurance', 'Core stamina'], ARRAY['Higher leg position', 'Slower pace'], ARRAY['Keep lower back pressed down'], 'free', 11);

  -- BALANCE EXERCISES (10 exercises)
  INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, description, instructions, benefits, modifications, cautions, tier_required, display_order) VALUES
  ('Single-Leg Stand', balance_id, 1, 30, 'Basic balance challenge', 'Stand on one leg, hold position. Switch legs.', ARRAY['Balance improvement', 'Ankle strength', 'Body awareness'], ARRAY['Hold onto wall', 'Eyes open'], ARRAY['Use stable surface'], 'free', 1),
  ('Tree Pose', balance_id, 2, 45, 'Yoga balance posture', 'Stand on one leg, place other foot on inner thigh. Hands in prayer or overhead.', ARRAY['Balance training', 'Hip flexibility', 'Focus and concentration'], ARRAY['Foot on calf instead', 'Hold support'], ARRAY['Never place foot on knee'], 'free', 2),
  ('Warrior III', balance_id, 3, 30, 'Yoga balance pose with hip hinge', 'Balance on one leg, hinge forward with back leg lifting, arms extended.', ARRAY['Balance and strength', 'Hamstring engagement', 'Body alignment'], ARRAY['Hold chair', 'Hands on hips'], ARRAY['Keep hips level'], 'free', 3),
  ('Single-Leg Deadlift Reach', balance_id, 3, 45, 'Balance with forward reaching', 'Stand on one leg, reach toward floor with opposite hand. Return to standing.', ARRAY['Dynamic balance', 'Hamstring strength', 'Coordination'], ARRAY['Shallow reach', 'Hold support'], ARRAY['Controlled movement'], 'free', 4),
  ('Eyes Closed Balance', balance_id, 2, 30, 'Balance challenge without vision', 'Stand on one leg with eyes closed. Hold position.', ARRAY['Proprioception', 'Balance confidence', 'Vestibular training'], ARRAY['Start with eyes barely closed', 'Hold support initially'], ARRAY['Safe environment only'], 'premium', 5),
  ('BOSU Ball Stand', balance_id, 3, 45, 'Unstable surface balance (simulated)', 'Imagine standing on unstable surface, engage stabilizers. Hold position.', ARRAY['Ankle stability', 'Core activation', 'Balance enhancement'], ARRAY['Both feet on ground', 'Eyes open'], ARRAY['Progress gradually'], 'premium', 6),
  ('Single-Leg Clock Reach', balance_id, 3, 60, 'Multi-directional balance challenge', 'Stand on one leg, reach other leg to clock positions (12, 3, 6, 9).', ARRAY['Multi-plane balance', 'Hip strength', 'Coordination'], ARRAY['Smaller reaches', 'Hold support'], ARRAY['Controlled movements'], 'premium', 7),
  ('Airplane Balance', balance_id, 2, 30, 'Flying balance pose', 'Balance on one leg, arms out to sides like airplane. Tilt side to side.', ARRAY['Balance fun', 'Core engagement', 'Spatial awareness'], ARRAY['Less tilting', 'Hold support'], ARRAY['Clear space around you'], 'free', 8),
  ('Tandem Stand', balance_id, 2, 30, 'Heel-to-toe balance', 'Stand with one foot directly in front of other, heel to toe. Hold.', ARRAY['Balance refinement', 'Ankle stability', 'Gait improvement'], ARRAY['Smaller gap between feet', 'Hold wall'], ARRAY['Progress from easier stances'], 'free', 9),
  ('Star Balance', balance_id, 4, 45, 'Advanced balance with reaching', 'Balance on one leg, reach arms and legs out in star shape. Hold.', ARRAY['Maximum balance challenge', 'Full-body control', 'Coordination mastery'], ARRAY['Partial star', 'Hold support'], ARRAY['Master simpler balances first'], 'premium', 10);

  -- ENDURANCE EXERCISES (10 exercises)
  INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, description, instructions, benefits, modifications, cautions, tier_required, display_order) VALUES
  ('Marching in Place', endurance_id, 1, 60, 'Low-impact continuous movement', 'March in place, lifting knees and swinging arms naturally.', ARRAY['Cardiovascular warmup', 'Low-impact cardio', 'Endurance building'], ARRAY['Smaller knee lifts', 'Slower pace'], ARRAY['Good starting point for beginners'], 'free', 1),
  ('Step Touch', endurance_id, 1, 60, 'Side-to-side stepping pattern', 'Step to one side and touch, then step back. Repeat rhythmically.', ARRAY['Cardio endurance', 'Coordination', 'Low-impact option'], ARRAY['No arm movement', 'Smaller steps'], ARRAY['Maintain steady rhythm'], 'free', 2),
  ('Shadow Boxing', endurance_id, 2, 60, 'Continuous punching movements', 'Throw punches in air with footwork, like boxing training.', ARRAY['Upper body endurance', 'Cardio workout', 'Stress relief'], ARRAY['Slower punches', 'Remove footwork'], ARRAY['Keep shoulders relaxed'], 'free', 3),
  ('Squat Pulses', endurance_id, 2, 45, 'Small range squat movements', 'Hold squat position, pulse up and down in small movements.', ARRAY['Leg endurance', 'Time under tension', 'Mental toughness'], ARRAY['Shallower squat', 'Hold static instead'], ARRAY['Maintain form throughout'], 'free', 4),
  ('Plank to Downward Dog', endurance_id, 3, 60, 'Flowing movement between positions', 'Move between plank position and downward dog pose continuously.', ARRAY['Full-body endurance', 'Flexibility', 'Flow training'], ARRAY['Slow down pace', 'Hold each position longer'], ARRAY['Maintain control'], 'free', 5),
  ('Continuous Jumping', endurance_id, 3, 45, 'Sustained jumping exercise', 'Jump continuously with both feet, maintaining steady rhythm.', ARRAY['Calf endurance', 'Cardiovascular fitness', 'Explosive power'], ARRAY['Lower jump height', 'Jump rope simulation'], ARRAY['Land softly'], 'premium', 6),
  ('Bear Crawl', endurance_id, 3, 60, 'Ground-based locomotion', 'Crawl forward on hands and feet, keeping hips low.', ARRAY['Full-body endurance', 'Core strength', 'Coordination'], ARRAY['Crawl slower', 'Higher hip position'], ARRAY['Clear space needed'], 'premium', 7),
  ('Inchworm Walks', endurance_id, 3, 60, 'Walking plank variation', 'Stand, walk hands out to plank, walk feet to hands, stand up. Repeat.', ARRAY['Full-body endurance', 'Flexibility', 'Core strength'], ARRAY['Don''t walk hands out as far', 'Slower pace'], ARRAY['Hamstring flexibility helpful'], 'premium', 8),
  ('Wall Sit Hold Extended', endurance_id, 4, 60, 'Extended isometric hold', 'Wall sit position held for extended duration.', ARRAY['Quad endurance', 'Mental toughness', 'Isometric strength'], ARRAY['Higher angle', 'Shorter duration'], ARRAY['Build up gradually'], 'premium', 9),
  ('Plank Walk-Outs', endurance_id, 4, 60, 'Dynamic plank movement', 'From plank, walk hands forward and back while maintaining form.', ARRAY['Core endurance', 'Shoulder strength', 'Body control'], ARRAY['Smaller range', 'Slower movement'], ARRAY['Advanced core exercise'], 'premium', 10);

END $$;