-- ==========================================
-- PHASE 1: EXERCISE DATA MIGRATION
-- Replace all exercise categories and exercises
-- ==========================================

-- Step 1: Delete all existing exercises (generic exercises)
DELETE FROM exercises;

-- Step 2: Delete all existing exercise categories
DELETE FROM exercise_categories;

-- Step 3: Create 6 new exercise categories with correct icons and display order
INSERT INTO exercise_categories (name, description, icon_name, display_order) VALUES
('Cardio & Walking', NULL, 'Zap', 1),
('Core & Balance', NULL, 'Target', 2),
('Leg Strength', NULL, 'Dumbbell', 3),
('Seated Movement', NULL, 'Armchair', 4),
('Standing Movement', NULL, 'PersonStanding', 5),
('Wall Sits', NULL, 'Layers', 6);

-- Step 4: Insert all 60 exercises from inner_fire_exercise_library.json
-- Core & Balance exercises (10)
INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, tier_required, description, instructions, benefits, cautions, modifications, is_active, display_order) VALUES
('Wall Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 1, 30, 'free', 'Plank performed at an incline against a wall to build initial core strength and proper form.', ARRAY['Stand facing a wall, about arm''s length away.', 'Place your forearms on the wall at shoulder height, slightly wider than shoulder-width apart.', 'Walk your feet back until your body forms a straight diagonal line from head to heels.', 'Engage your core and glutes to maintain a rigid posture.', 'Hold this position for 20-30 seconds, breathing steadily.'], NULL, NULL, NULL, true, 1),
('Knee Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 1, 30, 'free', 'A beginner-friendly plank variation performed on knees that reduces load while building core strength.', ARRAY['Start on all fours with your hands directly under your shoulders.', 'Lower down to your forearms, keeping your elbows under your shoulders.', 'Keep your knees on the floor and extend your feet behind you.', 'Form a straight line from your head to your knees.', 'Engage your core and hold for 20-30 seconds.'], NULL, NULL, NULL, true, 2),
('Forearm Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 2, 30, 'free', 'The foundation of all plank exercises. Hold rigid position on forearms and toes.', ARRAY['Lie face down, then lift your body onto your forearms and toes.', 'Position your elbows directly under your shoulders.', 'Keep your body in a straight line from head to heels.', 'Engage your core, squeeze your glutes, and avoid letting your hips sag.', 'Hold for 30-60 seconds, breathing steadily.'], NULL, NULL, NULL, true, 3),
('High Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 2, 30, 'free', 'A push-up position plank that engages arms and shoulders more intensively.', ARRAY['Start in a push-up position with hands directly under your shoulders.', 'Keep your arms straight and your body in a straight line from head to heels.', 'Engage your core and avoid letting your hips drop or rise.', 'Keep your neck neutral by looking at the floor slightly ahead of your hands.', 'Hold for 30-60 seconds.'], NULL, NULL, NULL, true, 4),
('Side Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 3, 30, 'free', 'Target your obliques and improve lateral core strength and balance.', ARRAY['Lie on your side with your elbow directly under your shoulder.', 'Stack your feet or stagger them for more stability.', 'Lift your hips off the ground, forming a straight line from head to feet.', 'Keep your core engaged and avoid letting your hips sag.', 'Hold for 20-30 seconds per side.'], NULL, NULL, NULL, true, 5),
('Plank with Leg Lift', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 3, 30, 'free', 'Plank with alternating leg lifts to increase core activation and stability challenge.', ARRAY['Start in a forearm plank position with your body in a straight line.', 'Engage your core and lift one leg off the ground, keeping it straight.', 'Hold the lifted position for 1-2 seconds.', 'Lower the leg back down with control and repeat with the other leg.', 'Alternate legs for 30-45 seconds.'], NULL, NULL, NULL, true, 6),
('Plank with Arm Reach', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 4, 30, 'premium', 'Plank with arm extensions forward to challenge balance and shoulder stability.', ARRAY['Start in a high plank position with hands under your shoulders.', 'Engage your core and slowly extend one arm straight forward.', 'Hold for 1-2 seconds, maintaining a stable torso.', 'Return your hand to the starting position and repeat with the other arm.', 'Alternate arms for 30-45 seconds.'], NULL, NULL, NULL, true, 7),
('Single-Arm Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 4, 30, 'premium', 'Plank with one arm removed to significantly increase core and shoulder stabilizer demands.', ARRAY['Start in a forearm plank position.', 'Shift your weight slightly and lift one forearm off the ground.', 'Extend the lifted arm forward or place your hand on your hip.', 'Keep your hips level and avoid rotating your torso.', 'Hold for 10-15 seconds per side.'], NULL, NULL, NULL, true, 8),
('Side Plank with Leg Lift', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 5, 30, 'premium', 'Advanced side plank variation with top leg raised to challenge core stability.', ARRAY['Start in a side plank position with your elbow under your shoulder.', 'Engage your core and lift your top leg toward the ceiling.', 'Keep your leg straight and your hips lifted.', 'Hold for 1-2 seconds, then lower with control.', 'Repeat for 20-30 seconds per side.'], NULL, NULL, NULL, true, 9),
('Single-Arm Single-Leg Plank', (SELECT id FROM exercise_categories WHERE name = 'Core & Balance'), 5, 30, 'premium', 'Ultimate plank challenge combining arm and leg removal for maximum core engagement.', ARRAY['Start in a high plank position.', 'Simultaneously lift one arm forward and the opposite leg backward.', 'Keep your body as stable as possible, avoiding rotation.', 'Hold for 5-10 seconds, then switch sides.', 'Alternate for 30-45 seconds.'], NULL, NULL, NULL, true, 10);

-- Leg Strength exercises (10)
INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, tier_required, description, instructions, benefits, cautions, modifications, is_active, display_order) VALUES
('Knee Raises (Lying)', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 1, 30, 'free', 'Introduction to core and hip flexor work that builds solid strength lying on your back.', ARRAY['Lie on your back with your hands at your sides or under your hips for support.', 'Bend your knees to about 90 degrees with your feet flat on the floor.', 'Engage your core and lift your knees toward your chest.', 'Lower your feet back down with control, keeping your lower back pressed to the floor.', 'Repeat for 20-30 repetitions.'], NULL, NULL, NULL, true, 1),
('Bent Knee Leg Lifts', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 1, 30, 'free', 'Lying leg lifts with bent knees to reduce difficulty while strengthening hip flexors.', ARRAY['Lie on your back with your hands at your sides.', 'Bend your knees and lift your feet off the ground so your thighs are perpendicular to the floor.', 'Engage your core and slowly lower your feet toward the floor without touching.', 'Lift your legs back to the starting position.', 'Repeat for 15-20 repetitions.'], NULL, NULL, NULL, true, 2),
('Alternating Leg Raises', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 2, 30, 'free', 'Bend on the way up and straighten before lowering to introduce straight leg raises.', ARRAY['Lie on your back with your legs extended and hands at your sides.', 'Bend one knee slightly as you lift that leg toward the ceiling.', 'Straighten the leg at the top, then bend it again as you lower it.', 'Alternate legs in a controlled, rhythmic motion.', 'Repeat for 20-30 repetitions (10-15 per leg).'], NULL, NULL, NULL, true, 3),
('Straight Leg Raises (Lying)', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 2, 30, 'free', 'Lying leg lifts with straight legs to build excellent core and hip flexor strength.', ARRAY['Lie on your back with your legs fully extended and hands at your sides.', 'Keep your legs straight and lift them toward the ceiling until they form a 90-degree angle with your torso.', 'Lower your legs slowly without letting them touch the floor.', 'Keep your lower back pressed to the floor throughout.', 'Repeat for 15-20 repetitions.'], NULL, NULL, NULL, true, 4),
('Side-Lying Leg Lifts', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 3, 30, 'free', 'Leg lifts performed while lying on your side to target hip abductors and glutes.', ARRAY['Lie on your side with your legs stacked and your head resting on your arm.', 'Keep your top leg straight and lift it toward the ceiling.', 'Hold for a moment at the top, then lower with control.', 'Avoid rolling your hips forward or backward.', 'Repeat for 15-20 repetitions per side.'], NULL, NULL, NULL, true, 5),
('Standing Leg Raises', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 3, 30, 'free', 'Leg raises performed while standing to improve balance and hip flexor strength.', ARRAY['Stand tall with your feet hip-width apart, holding onto a wall or chair for balance if needed.', 'Engage your core and lift one leg straight in front of you as high as comfortable.', 'Hold for a moment, then lower with control.', 'Keep your standing leg slightly bent and avoid leaning back.', 'Repeat for 12-15 repetitions per leg.'], NULL, NULL, NULL, true, 6),
('Single Leg Lift Holds', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 4, 30, 'premium', 'Static holds with one leg raised to build isometric strength and stability.', ARRAY['Lie on your back or stand tall, depending on your preference.', 'Lift one leg to about 45 degrees and hold it in place.', 'Keep the leg straight and engage your core to maintain stability.', 'Hold for 15-30 seconds per leg.', 'Switch sides and repeat.'], NULL, NULL, NULL, true, 7),
('Leg Lifts with Twist', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 4, 30, 'premium', 'Leg lifts with rotational movement to engage obliques and increase difficulty.', ARRAY['Lie on your back with your legs extended.', 'Lift both legs toward the ceiling, keeping them straight.', 'Lower your legs to one side in a controlled motion, keeping your shoulders on the floor.', 'Return to center, then lower to the other side.', 'Repeat for 10-15 repetitions per side.'], NULL, NULL, NULL, true, 8),
('Hanging Knee Raises', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 5, 30, 'premium', 'Knee raises while hanging from a bar to build advanced core and grip strength.', ARRAY['Hang from a pull-up bar with your arms fully extended and your feet off the ground.', 'Engage your core and lift your knees toward your chest.', 'Hold for a moment at the top, then lower with control.', 'Avoid swinging your body; keep the movement controlled.', 'Repeat for 10-15 repetitions.'], NULL, NULL, NULL, true, 9),
('Hanging Leg Raises', (SELECT id FROM exercise_categories WHERE name = 'Leg Strength'), 5, 30, 'premium', 'Straight leg raises while hanging to form a right angle - an advanced strength feat.', ARRAY['Hang from a pull-up bar with your arms fully extended.', 'Keep your legs straight and lift them until they form a 90-degree angle with your torso.', 'Hold for a moment at the top, then lower slowly.', 'Avoid swinging; use controlled movements throughout.', 'Repeat for 8-12 repetitions.'], NULL, NULL, NULL, true, 10);

-- Seated Movement exercises (10)
INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, tier_required, description, instructions, benefits, cautions, modifications, is_active, display_order) VALUES
('Seated Ankle Circles', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 1, 30, 'free', 'Simple ankle mobility exercise performed while seated to improve circulation.', ARRAY['Sit in a chair with your feet flat on the floor.', 'Lift one foot slightly off the ground.', 'Rotate your ankle in a circular motion, making large circles.', 'Complete 10 circles in one direction, then 10 in the other.', 'Switch feet and repeat.'], NULL, NULL, NULL, true, 1),
('Seated Shoulder Rolls', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 1, 30, 'free', 'Gentle shoulder mobility exercise to reduce tension and improve range of motion.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Roll your shoulders forward in a circular motion for 10 repetitions.', 'Reverse the direction and roll your shoulders backward for 10 repetitions.', 'Keep the movements slow and controlled.', 'Breathe deeply throughout.'], NULL, NULL, NULL, true, 2),
('Seated Marching', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 1, 30, 'free', 'Lift knees alternately while seated to engage core and hip flexors.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Lift one knee toward your chest, then lower it back down.', 'Alternate legs in a marching motion.', 'Keep your core engaged and your back straight.', 'Continue for 30-60 seconds.'], NULL, NULL, NULL, true, 3),
('Seated Arm Raises', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 2, 30, 'free', 'Lifting arms overhead while seated to strengthen shoulders and improve mobility.', ARRAY['Sit tall in a chair with your arms at your sides.', 'Slowly raise both arms out to the sides and overhead.', 'Lower your arms back down with control.', 'Keep your movements smooth and avoid shrugging your shoulders.', 'Repeat for 12-15 repetitions.'], NULL, NULL, NULL, true, 4),
('Seated Torso Twist', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 2, 30, 'free', 'Gentle spinal rotation while seated to improve core flexibility and strength.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Place your hands behind your head or cross them over your chest.', 'Rotate your torso to one side, keeping your hips facing forward.', 'Return to center and rotate to the other side.', 'Repeat for 10-15 repetitions per side.'], NULL, NULL, NULL, true, 5),
('Seated Leg Extensions', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 2, 30, 'free', 'Straighten and bend legs while seated to strengthen quadriceps.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Extend one leg straight out in front of you, lifting your foot off the ground.', 'Hold for a moment, then lower back down.', 'Alternate legs or complete all repetitions on one side before switching.', 'Repeat for 12-15 repetitions per leg.'], NULL, NULL, NULL, true, 6),
('Seated Side Bends', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 3, 30, 'free', 'Lateral flexion of spine while seated to target obliques and improve flexibility.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Raise one arm overhead and lean to the opposite side.', 'Feel the stretch along your side, then return to center.', 'Switch arms and lean to the other side.', 'Repeat for 10-12 repetitions per side.'], NULL, NULL, NULL, true, 7),
('Seated Knee-to-Chest', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 3, 30, 'free', 'Hip flexor strengthening exercise bringing knees toward chest while seated.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Lift one knee toward your chest, wrapping your hands around your shin if comfortable.', 'Hold for 2-3 seconds, feeling the stretch in your hip and lower back.', 'Lower your foot back down and repeat with the other leg.', 'Repeat for 10-12 repetitions per leg.'], NULL, NULL, NULL, true, 8),
('Seated Oblique Twists', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 4, 30, 'premium', 'Advanced rotational core exercise performed while seated with controlled movement.', ARRAY['Sit tall in a chair with your feet flat on the floor.', 'Clasp your hands together in front of your chest.', 'Rotate your torso to one side, bringing your hands toward that side.', 'Return to center and rotate to the other side.', 'Repeat for 15-20 repetitions per side.'], NULL, NULL, NULL, true, 9),
('Chair Squats', (SELECT id FROM exercise_categories WHERE name = 'Seated Movement'), 4, 30, 'premium', 'Standing up and sitting down from chair repeatedly to build leg strength.', ARRAY['Stand in front of a chair with your feet shoulder-width apart.', 'Lower yourself down as if sitting in the chair, lightly touching the seat.', 'Stand back up by pushing through your heels.', 'Keep your chest up and your knees tracking over your toes.', 'Repeat for 12-15 repetitions.'], NULL, NULL, NULL, true, 10);

-- Standing Movement exercises (10)
INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, tier_required, description, instructions, benefits, cautions, modifications, is_active, display_order) VALUES
('Arm Circles', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 1, 30, 'free', 'Make large circles with both arms to warm up shoulders and improve mobility.', ARRAY['Stand tall with your feet shoulder-width apart.', 'Extend your arms out to the sides at shoulder height.', 'Make small circles with your arms, gradually increasing the size.', 'Complete 15-20 circles forward, then reverse direction.', 'Keep your core engaged throughout.'], NULL, NULL, NULL, true, 1),
('Calf Raises', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 1, 30, 'free', 'Rising up on toes to strengthen calves and improve ankle stability.', ARRAY['Stand tall with your feet hip-width apart.', 'Rise up onto the balls of your feet, lifting your heels as high as possible.', 'Hold for a moment at the top, then lower back down with control.', 'Use a wall or chair for balance if needed.', 'Repeat for 15-20 repetitions.'], NULL, NULL, NULL, true, 2),
('Standing Side Bends', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 1, 30, 'free', 'Lateral torso stretches to improve flexibility and engage obliques.', ARRAY['Stand tall with your feet shoulder-width apart and your arms at your sides.', 'Slide one hand down your leg toward your knee, bending to the side.', 'Return to the starting position and repeat on the other side.', 'Keep your movements controlled and avoid leaning forward or backward.', 'Repeat for 12-15 repetitions per side.'], NULL, NULL, NULL, true, 3),
('Standing Knee Raises', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 2, 30, 'free', 'Alternating knee raises to engage hip flexors and improve balance.', ARRAY['Stand tall with your feet hip-width apart.', 'Lift one knee toward your chest as high as comfortable.', 'Lower it back down and immediately lift the other knee.', 'Alternate legs in a controlled, rhythmic motion.', 'Continue for 30-60 seconds.'], NULL, NULL, NULL, true, 4),
('Standing Torso Twists', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 2, 30, 'free', 'Rotational core movements to improve spinal mobility and core strength.', ARRAY['Stand tall with your feet shoulder-width apart and your hands on your hips or crossed over your chest.', 'Rotate your torso to one side, keeping your hips facing forward.', 'Return to center and rotate to the other side.', 'Keep the movement controlled and avoid jerking.', 'Repeat for 15-20 repetitions per side.'], NULL, NULL, NULL, true, 5),
('Bodyweight Squats', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 2, 30, 'free', 'Basic squatting movement to strengthen legs, glutes, and core.', ARRAY['Stand with your feet shoulder-width apart and your toes slightly turned out.', 'Lower your hips back and down as if sitting in a chair.', 'Keep your chest up and your knees tracking over your toes.', 'Push through your heels to return to standing.', 'Repeat for 12-15 repetitions.'], NULL, NULL, NULL, true, 6),
('Standing Leg Swings', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 3, 30, 'free', 'Dynamic leg swinging forward and back to improve hip mobility and flexibility.', ARRAY['Stand next to a wall or chair for support.', 'Swing one leg forward and backward in a controlled motion.', 'Keep your torso upright and avoid excessive leaning.', 'Complete 12-15 swings per leg.', 'Switch sides and repeat.'], NULL, NULL, NULL, true, 7),
('Standing Side Leg Raises', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 3, 30, 'free', 'Lateral leg lifts to strengthen glutes and hip abductors while improving balance.', ARRAY['Stand tall with your feet together, holding onto a wall or chair for balance.', 'Lift one leg out to the side as high as comfortable, keeping it straight.', 'Hold for a moment, then lower with control.', 'Avoid leaning to the side; keep your torso upright.', 'Repeat for 12-15 repetitions per leg.'], NULL, NULL, NULL, true, 8),
('Single Leg Balance', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 4, 30, 'premium', 'Balance challenge on one leg to improve stability and proprioception.', ARRAY['Stand tall with your feet together.', 'Lift one foot off the ground and balance on the other leg.', 'Hold for 20-30 seconds, keeping your core engaged.', 'Use a wall or chair for support if needed.', 'Switch legs and repeat.'], NULL, NULL, NULL, true, 9),
('Wall Push-Ups', (SELECT id FROM exercise_categories WHERE name = 'Standing Movement'), 4, 30, 'premium', 'Incline push-ups against wall to build upper body strength with reduced difficulty.', ARRAY['Stand facing a wall, about arm''s length away.', 'Place your hands on the wall at shoulder height, slightly wider than shoulder-width apart.', 'Lean forward and bend your elbows, bringing your chest toward the wall.', 'Push back to the starting position.', 'Repeat for 12-15 repetitions.'], NULL, NULL, NULL, true, 10);

-- Cardio & Walking exercises (12)
INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, tier_required, description, instructions, benefits, cautions, modifications, is_active, display_order) VALUES
('Gentle Arm Swings While Walking', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 1, 30, 'free', 'Walking with coordinated arm movements to warm up and improve circulation.', ARRAY['Begin walking at a comfortable pace.', 'Swing your arms naturally forward and backward in rhythm with your steps.', 'Keep your shoulders relaxed and your movements smooth.', 'Continue for 5-10 minutes as a warm-up or light cardio activity.', 'Focus on coordinating your breath with your movement.'], NULL, NULL, NULL, true, 1),
('Slow Indoor Walking', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 1, 30, 'free', 'Gentle walking pace indoors for beginners or warm-up. Can extend beyond 5 minutes.', ARRAY['Walk at a gentle, comfortable pace indoors.', 'Keep your posture upright and your core engaged.', 'Swing your arms naturally at your sides.', 'Continue for 5-15 minutes, or longer if comfortable.', 'This is ideal for beginners or as a recovery activity.'], NULL, NULL, NULL, true, 2),
('Standing Marching in Place', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 1, 30, 'free', 'Marching without moving forward to elevate heart rate in limited space.', ARRAY['Stand tall with your feet hip-width apart.', 'Lift one knee toward your chest, then lower it and lift the other knee.', 'March in place at a comfortable pace.', 'Swing your arms naturally to engage your upper body.', 'Continue for 3-5 minutes.'], NULL, NULL, NULL, true, 3),
('Regular Walking', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 2, 30, 'free', 'Comfortable walking at a moderate sustainable pace. Recommended 30 minutes daily for health benefits.', ARRAY['Walk at a comfortable, sustainable pace outdoors or indoors.', 'Keep your posture upright with your shoulders back and core engaged.', 'Swing your arms naturally at your sides.', 'Aim for 30 minutes daily for optimal health benefits.', 'This is a foundational low-impact cardio exercise.'], NULL, NULL, NULL, true, 4),
('Walking with Arm Circles', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 2, 30, 'free', 'Walking combined with arm circles to engage upper body and increase intensity.', ARRAY['Begin walking at a moderate pace.', 'Extend your arms out to the sides and make small circles as you walk.', 'Gradually increase the size of the circles.', 'Continue for 5-10 minutes, alternating between forward and backward circles.', 'This adds upper body engagement to your walk.'], NULL, NULL, NULL, true, 5),
('Walking with High Knees', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 2, 30, 'free', 'Walking with exaggerated knee lifts to increase intensity and engage hip flexors.', ARRAY['Walk forward while lifting your knees as high as comfortable with each step.', 'Keep your core engaged and your posture upright.', 'Swing your arms naturally to maintain balance.', 'Continue for 3-5 minutes.', 'This increases the intensity of your walking workout.'], NULL, NULL, NULL, true, 6),
('Brisk Walking', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 3, 30, 'free', 'Fast-paced walking to elevate heart rate and build cardiovascular endurance. Can extend to 30+ minutes.', ARRAY['Walk at a fast pace that elevates your heart rate but still allows you to talk.', 'Keep your posture upright and your core engaged.', 'Swing your arms vigorously to increase intensity.', 'Aim for 20-30 minutes for cardiovascular benefits.', 'This is an excellent low-impact cardio workout.'], NULL, NULL, NULL, true, 7),
('Stair Step-Ups', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 3, 30, 'free', 'Stepping up and down stairs to build leg strength and cardiovascular fitness.', ARRAY['Stand facing a staircase or a sturdy step.', 'Step up with one foot, then bring the other foot up to meet it.', 'Step back down with the same foot, then the other.', 'Alternate your leading foot every few repetitions.', 'Continue for 3-5 minutes.'], NULL, NULL, NULL, true, 8),
('Walking Lunges', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 3, 30, 'free', 'Lunges while moving forward to build leg strength and improve balance.', ARRAY['Stand tall with your feet hip-width apart.', 'Step forward with one leg and lower your hips until both knees are bent at about 90 degrees.', 'Push through your front heel to bring your back leg forward into the next lunge.', 'Continue moving forward in a controlled, alternating lunge pattern.', 'Repeat for 10-15 lunges per leg.'], NULL, NULL, NULL, true, 9),
('Fast-Paced Marching', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 4, 30, 'premium', 'High-intensity marching in place with arm movements to maximize cardio benefit.', ARRAY['Stand tall and march in place at a rapid pace.', 'Lift your knees as high as comfortable with each step.', 'Swing your arms vigorously to increase intensity.', 'Keep your core engaged and your breathing controlled.', 'Continue for 3-5 minutes.'], NULL, NULL, NULL, true, 10),
('Side Steps with Arms', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 4, 30, 'premium', 'Side-to-side stepping motion with coordinated arm movements for cardio and coordination.', ARRAY['Stand tall with your feet together.', 'Step to the side with one foot, then bring the other foot to meet it.', 'As you step, raise your arms out to the sides or overhead.', 'Continue side-stepping in one direction for 10-15 steps, then reverse.', 'Repeat for 3-5 minutes.'], NULL, NULL, NULL, true, 11),
('Walking with Resistance', (SELECT id FROM exercise_categories WHERE name = 'Cardio & Walking'), 5, 30, 'premium', 'Walking with added weight (backpack) to increase intensity and build endurance.', ARRAY['Put on a backpack with 5-15 pounds of weight (books, water bottles, etc.).', 'Walk at a moderate to brisk pace outdoors or indoors.', 'Keep your posture upright and your core engaged.', 'The added weight increases the intensity and builds endurance.', 'Aim for 20-30 minutes.'], NULL, NULL, NULL, true, 12);

-- Wall Sits exercises (8)
INSERT INTO exercises (name, category_id, difficulty_level, duration_seconds, tier_required, description, instructions, benefits, cautions, modifications, is_active, display_order) VALUES
('Shallow Wall Sit (45-degree)', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 1, 30, 'free', 'A beginner-friendly wall sit performed at a 45-degree angle to reduce intensity while building leg strength.', ARRAY['Stand with your back against a wall and your feet about 1-2 feet away from the wall.', 'Slide down the wall until your knees are bent at about 45 degrees (not a full 90-degree angle).', 'Keep your back flat against the wall and your feet flat on the floor.', 'Hold this position for 20-30 seconds.', 'This is a beginner-friendly variation that reduces intensity.'], NULL, NULL, NULL, true, 1),
('Standard Wall Sit', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 2, 30, 'free', 'Basic wall sit with back against wall and legs at 90-degree angle to build quad strength.', ARRAY['Stand with your back against a wall and your feet about 2 feet away from the wall.', 'Slide down the wall until your thighs are parallel to the floor (90-degree angle at the knees).', 'Keep your back flat against the wall and your feet flat on the floor.', 'Hold this position for 30-60 seconds.', 'Focus on keeping your core engaged throughout.'], NULL, NULL, NULL, true, 2),
('Wall Sit with Arms Crossed', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 2, 30, 'free', 'Wall sit with arms crossed over chest to remove arm support and increase core engagement.', ARRAY['Perform a standard wall sit with your back against the wall and your thighs parallel to the floor.', 'Cross your arms over your chest instead of resting them at your sides.', 'This removes arm support and increases core engagement.', 'Hold for 30-60 seconds.', 'Keep your breathing steady.'], NULL, NULL, NULL, true, 3),
('Narrow Stance Wall Sit', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 3, 30, 'free', 'Wall sit with feet close together to target glutes and hamstrings differently.', ARRAY['Stand with your back against a wall and bring your feet close together.', 'Slide down into a wall sit position with your thighs parallel to the floor.', 'Keep your knees and ankles touching.', 'Hold for 30-60 seconds.', 'This variation targets the glutes and hamstrings more intensely.'], NULL, NULL, NULL, true, 4),
('Wall Sit with Heels Raised', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 3, 30, 'free', 'Wall sit on toes to add calf work and increase quad engagement.', ARRAY['Perform a standard wall sit with your back against the wall.', 'Lift your heels off the ground, balancing on the balls of your feet.', 'Hold this position for 20-40 seconds.', 'This adds calf work and increases quad engagement.', 'Lower your heels if you need a brief rest.'], NULL, NULL, NULL, true, 5),
('Wall Sit with Arm Raises', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 4, 30, 'premium', 'Wall sit combined with overhead arm movements to engage shoulders and core.', ARRAY['Perform a standard wall sit with your back against the wall.', 'Slowly raise your arms overhead, then lower them back down.', 'Repeat the arm raises for 10-15 repetitions while holding the wall sit.', 'This engages your shoulders and core while maintaining the leg hold.', 'Keep your breathing controlled.'], NULL, NULL, NULL, true, 6),
('Wall Sit with Leg Extensions', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 4, 30, 'premium', 'Wall sit with alternating leg lifts to significantly increase difficulty and balance challenge.', ARRAY['Perform a standard wall sit with your back against the wall.', 'Lift one leg straight out in front of you, holding it parallel to the floor.', 'Hold for 3-5 seconds, then lower and switch legs.', 'Alternate legs for 30-45 seconds.', 'This significantly increases the difficulty and balance challenge.'], NULL, NULL, NULL, true, 7),
('Single Leg Wall Sit', (SELECT id FROM exercise_categories WHERE name = 'Wall Sits'), 5, 30, 'premium', 'Wall sit performed on one leg - an advanced strength and balance challenge.', ARRAY['Perform a standard wall sit with your back against the wall.', 'Lift one leg off the ground and extend it straight in front of you.', 'Hold this single-leg position for 10-20 seconds.', 'Switch legs and repeat.', 'This is an advanced strength and balance challenge.'], NULL, NULL, NULL, true, 8);

-- ==========================================
-- PHASE 2: CLEANUP - DROP OLD TABLES
-- ==========================================

-- Drop exercise_families table (no longer needed)
DROP TABLE IF EXISTS exercise_families CASCADE;

-- Drop plank_exercises table (replaced by new exercises table)
DROP TABLE IF EXISTS plank_exercises CASCADE;